#! /bin/bash


libcVersionList=(2.23 2.24 2.26 2.27 2.28 2.29 2.30 2.31 2.32 2.33 2.34)

conName=
for i in ${libcVersionList[*]};
do
    sudo docker ps -a --format "{{.Names}}" | grep -q "$i"
    if [ $? -ne 0 ] ;then
        continue
    else
        conName=$i
        break
    fi
done

echo $conName

if [ ! $conName ]; then  
    
    echo "Unkonw error"
else
    echo "Get"
    sudo docker exec -it --privileged=true $conName /bin/bash -c "/usr/bin/dockerGDBIn && /bin/bash"
fi

